import { useCallback, useEffect, useState } from 'react';

import { locationService } from '@grafana/runtime';
import { Page } from 'app/core/components/Page/Page';
import { type SettingsPageProps } from 'app/features/dashboard/components/DashboardSettings/types';
import { useDispatch, useSelector } from 'app/types/store';

import { VariablesUnknownTable } from '../inspect/VariablesUnknownTable';
import { toKeyedAction } from '../state/keyedVariablesReducer';
import { getEditorVariables, getVariablesState } from '../state/selectors';
import { changeVariableOrder, duplicateVariable, removeVariable } from '../state/sharedReducer';
import { type KeyedVariableIdentifier } from '../state/types';
import { toKeyedVariableIdentifier, toVariablePayload } from '../utils';

import { ConfirmDeleteModal } from './ConfirmDeleteModal';
import { VariableEditorEditor } from './VariableEditorEditor';
import { VariableEditorList } from './VariableEditorList';
import { createNewVariable, initListMode } from './actions';

/**
 * VariableEditorContainer renders the dashboard's variable editor page.
 *
 * Converted from a `PureComponent` wrapped by `connect(mapStateToProps, mapDispatchToProps)`
 * to a hooks-based functional component per AAP Cohort 1:
 * - `connect` HOC -> `useSelector` / `useDispatch` from `app/types/store`.
 * - Class state `{ variableId }` -> `useState<KeyedVariableIdentifier | undefined>`.
 * - `componentDidMount` -> `useEffect(fn, [dashboard.uid])` invoking `initListMode`.
 * - `bindActionCreators` thunk dispatches -> inlined `dispatch(...)` calls.
 *
 * Public API preserved: the file continues to export a `VariableEditorContainer`
 * symbol consumed by `DashboardSettings.tsx`. No prop interface changes; the
 * runtime Redux wiring and rendered children are unchanged.
 */
export function VariableEditorContainer({ dashboard, editIndex, sectionNav }: SettingsPageProps) {
  const dispatch = useDispatch();

  // Replaces `mapStateToProps` — re-evaluated whenever the relevant slice of the
  // store changes. Reads are scoped to the dashboard's keyed templating state.
  const variables = useSelector((state) => getEditorVariables(dashboard.uid, state));
  const { usagesNetwork, usages } = useSelector((state) => {
    const templatingState = getVariablesState(dashboard.uid, state);
    return {
      // `idInEditor` was selected by the original `mapStateToProps` but never read
      // in `render()`; we omit it from the destructured selector output without
      // changing observable behaviour.
      usagesNetwork: templatingState.inspect.usagesNetwork,
      usages: templatingState.inspect.usages,
    };
  });

  const [variableId, setVariableId] = useState<KeyedVariableIdentifier | undefined>(undefined);

  // Replaces `componentDidMount`. Re-runs only when the dashboard UID changes,
  // matching the original mount-time call site (the dashboard prop is stable
  // for the lifetime of this page in practice but we list it explicitly to
  // honour exhaustive-deps).
  useEffect(() => {
    dispatch(initListMode(dashboard.uid));
  }, [dispatch, dashboard.uid]);

  const onEditVariable = useCallback(
    (identifier: KeyedVariableIdentifier) => {
      const index = variables.findIndex((x) => x.id === identifier.id);
      locationService.partial({ editIndex: index });
    },
    [variables]
  );

  const onNewVariable = useCallback(() => {
    dispatch(createNewVariable(dashboard.uid));
  }, [dispatch, dashboard.uid]);

  const onChangeVariableOrder = useCallback(
    (identifier: KeyedVariableIdentifier, fromIndex: number, toIndex: number) => {
      dispatch(
        toKeyedAction(identifier.rootStateKey, changeVariableOrder(toVariablePayload(identifier, { fromIndex, toIndex })))
      );
    },
    [dispatch]
  );

  const onDuplicateVariable = useCallback(
    (identifier: KeyedVariableIdentifier) => {
      dispatch(
        toKeyedAction(
          identifier.rootStateKey,
          // `newId` is generated by the reducer when undefined. Casting `undefined` to
          // `string` here matches the original (pre-conversion) payload shape exactly;
          // we preserve the runtime contract verbatim.
          // eslint-disable-next-line @typescript-eslint/consistent-type-assertions -- preserved from the pre-conversion implementation; `newId` is filled in by the reducer
          duplicateVariable(toVariablePayload(identifier, { newId: undefined as unknown as string }))
        )
      );
    },
    [dispatch]
  );

  const onModalOpen = useCallback((identifier: KeyedVariableIdentifier) => {
    setVariableId(identifier);
  }, []);

  const onModalClose = useCallback(() => {
    setVariableId(undefined);
  }, []);

  const onRemoveVariable = useCallback(() => {
    if (!variableId) {
      return;
    }
    dispatch(toKeyedAction(variableId.rootStateKey, removeVariable(toVariablePayload(variableId, { reIndex: true }))));
    setVariableId(undefined);
  }, [dispatch, variableId]);

  const variableToEdit = editIndex != null ? variables[editIndex] : undefined;
  const node = sectionNav.node;
  const parentItem = node.parentItem;
  const subPageNav = variableToEdit ? { text: variableToEdit.name, parentItem } : parentItem;

  return (
    <Page navModel={sectionNav} pageNav={subPageNav}>
      {!variableToEdit && (
        <VariableEditorList
          variables={variables}
          onAdd={onNewVariable}
          onEdit={onEditVariable}
          onChangeOrder={onChangeVariableOrder}
          onDuplicate={onDuplicateVariable}
          onDelete={onModalOpen}
          usages={usages}
          usagesNetwork={usagesNetwork}
        />
      )}
      {!variableToEdit && variables.length > 0 && (
        <VariablesUnknownTable variables={variables} dashboard={dashboard} />
      )}
      {variableToEdit && <VariableEditorEditor identifier={toKeyedVariableIdentifier(variableToEdit)} />}
      <ConfirmDeleteModal
        isOpen={variableId !== undefined}
        varName={variableId?.id ?? ''}
        onConfirm={onRemoveVariable}
        onDismiss={onModalClose}
      />
    </Page>
  );
}
